# Generated by Django 3.0.4 on 2020-03-25 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('city', models.CharField(default=None, max_length=30, null=True)),
                ('born', models.DateField(default=None, null=True)),
                ('sex', models.CharField(choices=[('M', 'Mężczyzna'), ('F', 'Kobieta'), ('U', 'Nieokreślono')], default='U', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
