# Generated by Django 3.2.3 on 2022-03-06 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Adres e-mail')),
                ('city', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Miejscowość')),
                ('born', models.DateField(blank=True, default=None, null=True, verbose_name='Urodziny')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Mężczyzna'), ('F', 'Kobieta'), ('U', 'Nieokreślono')], default=None, max_length=1, null=True, verbose_name='Płeć')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
