# Generated by Django 3.0.4 on 2020-04-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200413_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Mężczyzna'), ('F', 'Kobieta'), ('U', 'Nieokreślono')], default=None, max_length=1, null=True, verbose_name='Płeć'),
        ),
    ]
