# Generated by Django 3.0.4 on 2020-04-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='forum_id',
            field=models.IntegerField(choices=[(11, 'Featured Sub1'), (12, 'Featured Sub2'), (13, 'Featured Sub3'), (14, 'Featured Sub4'), (15, 'Featured Sub5')], default=11),
            preserve_default=False,
        ),
    ]
