from django.urls import path
from . import views


app_name = 'forum'

urlpatterns = [
    path('',
         views.forum_home,
         name='main'),
    path('community/',
         views.forum_community,
         name='community'),
    path('featured/',
         views.forum_featured,
         name='featured'),
    path('featured/subpage1/',
         views.PostListView.as_view(subheading='Category1',
                                    forum_id=11),
         name='featured-subpage1'),
    path('featured/subpage2/',
         views.PostListView.as_view(subheading='Category2',
                                    forum_id=12),
         name='featured-subpage2'),
    path('featured/subpage3/',
         views.PostListView.as_view(subheading='Category3',
                                    forum_id=13),
         name='featured-subpage3'),
    path('featured/subpage4/',
         views.PostListView.as_view(subheading='Category4',
                                    forum_id=14),
         name='featured-subpage4'),
    path('featured/subpage5/',
         views.PostListView.as_view(subheading='Category5',
                                    forum_id=15),
         name='featured-subpage5'),
    path('featured/subpage1/create-post/',
         views.PostCreateView.as_view(forum_id=11),
         name='featured-subpage1-create-post'),
    path('featured/subpage2/create-post/',
         views.PostCreateView.as_view(forum_id=12),
         name='featured-subpage2-create-post'),
    path('featured/subpage3/create-post/',
         views.PostCreateView.as_view(forum_id=13),
         name='featured-subpage3-create-post'),
    path('featured/subpage4/create-post/',
         views.PostCreateView.as_view(forum_id=14),
         name='featured-subpage4-create-post'),
    path('featured/subpage5/create-post/',
         views.PostCreateView.as_view(forum_id=15),
         name='featured-subpage5-create-post'),
]