from django.urls import path
from . import views


urlpatterns = [
    path('',
         views.forum_home,
         name='forum-main'),
    path('community/',
         views.forum_community,
         name='forum-community'),
    path('featured/',
         views.forum_featured,
         name='forum-featured'),
    path('featured/subpage1/',
         views.FeaturedSubpageView.as_view(template_name='forum/featured-subpage1.html',
                                           subheading='Category1'),
         name='forum-featured-subpage1'),
    path('featured/subpage2/',
         views.FeaturedSubpageView.as_view(template_name='forum/featured-subpage2.html',
                                           subheading='Category2'),
         name='forum-featured-subpage2'),
    path('featured/subpage3/',
         views.FeaturedSubpageView.as_view(template_name='forum/featured-subpage3.html',
                                           subheading='Category3'),
         name='forum-featured-subpage3'),
    path('featured/subpage4/',
         views.FeaturedSubpageView.as_view(template_name='forum/featured-subpage4.html',
                                           subheading='Category4'),
         name='forum-featured-subpage4'),
    path('featured/subpage5/',
         views.FeaturedSubpageView.as_view(template_name='forum/featured-subpage5.html',
                                           subheading='Category5'),
         name='forum-featured-subpage5'),
    path('featured/subpage1/create-post/',
         views.PostCreateView.as_view(template_name='forum/post_create-featured-sub1.html',
                                      forum_id=11),
         name='featured-subpage1-create-post'),
    path('featured/subpage2/create-post/',
         views.PostCreateView.as_view(template_name='forum/post_create-featured-sub2.html',
                                      forum_id=12),
         name='featured-subpage2-create-post'),
]